### PR TITLE
Replace `--ignore-if-missing` with local file check

### LINKED ISSUE #138: Creating an AmazonLinux2 Swift SDK fails
Hello,

I wonder if it would be possible to generate an Amazon Linux 2 SDK ?
When I try to follow instruction to generate a SDK with a docker image, it generates files with the name `Ubuntu`

I surely missed something.

```
swift run swift-sdk-generator make-linux-sdk --from-container-image swift:6.0-amazonlinux2 --with-docker --swift-version 6.0.1-RELEASE                 
Building for debugging...
[1/1] Write swift-version-7BB6C6736DFA3E78.txt
Build of product 'swift-sdk-generator' complete! (0.33s)

Looking up configuration values...

Downloading required toolchain packages...
Using downloaded artifacts in these locations:
/Users/stormacq/Desktop/swift-sdk-generator/Artifacts/host_llvm_17.0.5_arm64-apple-macos15.0.0.tar.xz
/Users/stormacq/Desktop/swift-sdk-generator/Artifacts/host_swift_6.0.1-RELEASE_arm64-apple-macos15.0.0.pkg

Unpacking and copying Swift binaries for the host triple...
10608439 blocks

Launching a Docker container to copy Swift SDK for the target triple from it...

Copying Swift core libraries for the target triple into Swift SDK bundle...

Unpacking and copying `lld` linker...

Fixing up absolute symlinks...

Fixing absolute paths in `glibc.modulemap`...

Generating toolset JSON file...

Generating destination JSON file...

Generating .artifactbundle manifest file...

All done! Install the newly generated SDK with this command:
swift experimental-sdk install /Users/stormacq/Desktop/swift-sdk-generator/Bundles/6.0.1-RELEASE_ubuntu_jammy_aarch64.artifactbundle

After that, use the newly installed SDK when building with this command:
swift build --experimental-swift-sdk 6.0.1-RELEASE_ubuntu_jammy_aarch64

Time taken for this generator run: 3:08 seconds.
```

### LINKED ISSUE #181: rsync on macOS does not support the --ignore-missing-args option
#170 added the `--ignore-missing-args` flags to the `rsync` command.  Unfortunately the version of rsync provided by current versions of macOS (15.3) does not support this flag:

```
[23/23] Applying swift-sdk-generator
Build of product 'swift-sdk-generator' complete! (5.63s)
2025-02-13T14:01:38+0000 info org.swift.swift-sdk-generator : packageCount=11 [SwiftSDKGenerator] Downloading Ubuntu packages...
2025-02-13T14:01:39+0000 info org.swift.swift-sdk-generator : [SwiftSDKGenerator] Unpacking Swift distribution for the target triple...
2025-02-13T14:01:42+0000 info org.swift.swift-sdk-generator : [SwiftSDKGenerator] Copying Swift core libraries for the target triple into Swift SDK bundle...
rsync: --ignore-missing-args: unknown option
rsync error: syntax or usage error (code 1) at /AppleInternal/Library/BuildRoots/5bb93434-bef0-11ef-bef2-d285688f7a47/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(1337) [client=2.6.9]
```

### PR DESCRIPTION
**Pull request by xtremekforever**
This fixes #181.

Tested this locally by building SDKs. It works for building the SDK for armv7 using my build artifacts:

```
swift run swift-sdk-generator make-linux-sdk --swift-version 6.0.3-RELEASE --host x86_64-unknown-linux-gnu --target armv7-unknown-linux-gnueabihf --target-swift-package-path ~/Downloads/swift-6.0.3-RELEASE-ubuntu-jammy-armv7-install
```

And also building an SDK for aarch64 using official swift.org artifacts:

```
swift run swift-sdk-generator make-linux-sdk --swift-version 6.0.3-RELEASE --host x86_64-unknown-linux-gnu --target aarch64-unknown-linux-gnu
```

@MaxDesiatov @euanh

### CODE REVIEW

File: Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift [hunk 1]
```diff
@@ -109,16 +110,20 @@ extension SwiftSDKGenerator {
   func copyTargetSwift(from distributionPath: FilePath, sdkDirPath: FilePath) async throws {
     logger.info("Copying Swift core libraries for the target triple into Swift SDK bundle...")
 
-    for (pathWithinPackage, pathWithinSwiftSDK, ignoreIfMissing) in [
+    for (pathWithinPackage, pathWithinSwiftSDK, optional) in [
```
Comment (MaxDesiatov) [inline Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift:113]: I'd prefer adhering to the naming guidelines here
```suggestion
    for (pathWithinPackage, pathWithinSwiftSDK, isOptional) in [
```

Comment (xtremekforever) [reply Sources/SwiftSDKGenerator/Generator/SwiftSDKGenerator+Copy.swift:113]: Ah I also see another isOptional elsewhere. That was something I missed. Thanks

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Comment by MaxDesiatov** [comment]
@swift-ci test

**Review by MaxDesiatov — APPROVED** [review]
Seems reasonable to me, would be great get a review from Euan before merging.

**Comment by xtremekforever** [comment]
I did confirm this works fine on my MacBook Pro, but would be good to double check on another machine as well :)

**Comment by euanh** [comment]
> This fixes #138.

I think this should be https://github.com/swiftlang/swift-sdk-generator/issues/186

**Review by euanh — CHANGES_REQUESTED** [review]
> This fixes https://github.com/swiftlang/swift-sdk-generator/issues/138.

This PR is linked to #138 but I think it should be linked to #181

**Comment by xtremekforever** [comment]
Oops my bad. I updated the description. The PR is against #181 so I just fat fingered the description.

**Review by euanh — APPROVED** [review]

**Comment by MaxDesiatov** [comment]
@swift-ci test
